import { Product } from "./types";

export const products: Product[] = [
  // ------- TOPS -------
  {
    id: 1,
    title: "White Printed T-Shirt",
    image: ["/images/T-Shirt.webp"],
    slug: "White women TShirt",
    description: "Best quality T-Shirt for women",
    price: 150,
    catagory: "tops",
    size: ["S", "M", "L", "XL"],
    color: ["#ffffff", "#000000", "#e60000"],
    qty: 1,
    discount: 5,
  },
  {
    id: 2,
    title: "Black Printed T-Shirt",
    image: ["/images/T-shirt-02.avif"],
    slug: "Black women TShirt",
    description: "Best quality T-Shirt for women",
    price: 250,
    catagory: "tops",
    size: ["S", "M", "L", "XL"],
    color: ["#ffffff", "#000000", "#e60000"],
    qty: 2,
    discount: 10,
  },
  {
    id: 3,
    title: "White Cotton T-Shirt",
    image: ["/images/t-shirt-03.jpeg"],
    slug: "White Cotton women TShirt",
    description: "Premium cotton T-Shirt for everyday comfort",
    price: 200,
    catagory: "tops",
    size: ["S", "M", "L", "XL"],
    color: ["#ffffff", "#000000", "#e60000"],
    qty: 4,
    discount: 15,
  },
  {
    id: 4,
    title: "Ladies Green Tops",
    image: ["/images/Ladies-Green-Tops.webp"],
    slug: "Ladies Green Tops",
    description: "Stylish green tops for summer",
    price: 250,
    catagory: "tops",
    size: ["S", "M", "L", "XL"],
    color: ["#228B22", "#000000", "#e60000"],
    qty: 10,
    discount: 0,
  },
  {
    id: 5,
    title: "Ladies Green Relaxed Shirt",
    image: ["/images/Ladies-Green-Tops.jpeg"],
    slug: "Ladies Green Relaxed Shirt",
    description: "Soft and elegant V-neck with floral print",
    price: 275,
    catagory: "tops",
    size: ["S", "M", "L"],
    color: ["#ff69b4", "#000000"],
    qty: 5,
    discount: 5,
  },
  {
    id: 6,
    title: "Women Sleeveless Blouse",
    image: ["/images/top-blouse.jpeg"],
    slug: "Sleeveless Blouse Women",
    description: "Chic sleeveless blouse for formal wear",
    price: 320,
    catagory: "tops",
    size: ["M", "L", "XL"],
    color: ["#ffffff", "#808080"],
    qty: 6,
    discount: 10,
  },

  // ------- SHOES -------
  {
    id: 7,
    title: "women shoes",
    image: ["/images/shoes-01.avif"],
    slug: "British Style Women's Shoes",
    description: "Elegant British Style Shoes for casual wear",
    price: 1500,
    catagory: "shoes",
    size: ["S", "M", "L", "XL"],
    color: ["#ffffff", "#000000"],
    qty: 10,
    discount: 20,
  },
  {
    id: 8,
    title: "women white shoes",
    image: ["/images/shoes.avif"],
    slug: "Women's white Shoes",
    description: "Trendy white shoes for daily use",
    price: 1000,
    catagory: "shoes",
    size: ["S", "M", "L", "XL"],
    color: ["#ffffff"],
    qty: 8,
    discount: 15,
  },
  {
    id: 9,
    title: "Sneakers for Women",
    image: ["/images/shoes-02.webp"], 
    slug: "Women Sneakers Casual",
    description: "Lightweight and breathable sneakers",
    price: 1300,
    catagory: "shoes",
    size: ["S", "M", "L", "XL"],
    color: ["#000000", "#ff0000"],
    qty: 12,
    discount: 10,
  },
  {
    id: 10,
    title: "Chunky Sole Sandals",
    image: ["/images/sandals-chunky.jpeg"],
    slug: "Chunky Sole Sandals",
    description: "Comfort meets fashion in these chunky sandals",
    price: 1100,
    catagory: "shoes",
    size: ["S", "M", "L"],
    color: ["#f5f5dc", "#000000"],
    qty: 7,
    discount: 5,
  },
  {
    id: 11,
    title: "Formal Loafers",
    image: ["/images/formal-loafers.webp"],
    slug: "Formal Loafers Women",
    description: "Perfect for office or meetings",
    price: 1650,
    catagory: "shoes",
    size: ["M", "L", "XL"],
    color: ["#8b4513"],
    qty: 4,
    discount: 8,
  },
  {
    id: 12,
    title: "High Heel Sandals",
    image: ["/images/heels.webp"],
    slug: "High Heel Sandals",
    description: "Stylish heels to match your evening outfit",
    price: 1800,
    catagory: "shoes",
    size: ["S", "M", "L", "XL"],
    color: ["#e60000", "#000000"],
    qty: 6,
    discount: 15,
  },

  // ------- ACCESSORIES -------
  {
    id: 13,
    title: "women jewlry",
    image: ["/images/accessories.avif"],
    slug: "women accessories",
    description: "Elegant gold-plated jewelry",
    price: 300,
    catagory: "accessories",
    size: ["S", "M", "L", "XL"],
    color: ["#ffffff", "#000000", "#e60000"],
    qty: 5,
    discount: 10,
  },
  {
    id: 14,
    title: "Leather Handbag",
    image: ["/images/handbag.jpg"],
    slug: "leather handbag",
    description: "Premium leather handbag for all occasions",
    price: 2400,
    catagory: "accessories",
    size: ["M"],
    color: ["#000000", "#964B00"],
    qty: 2,
    discount: 5,
  },
  {
    id: 15,
    title: "Fashion Sunglasses",
    image: ["/images/sunglasses.jpeg"],
    slug: "fashion sunglasses",
    description: "UV protected modern sunglasses",
    price: 800,
    catagory: "accessories",
    size: ["S", "M"],
    color: ["#000000"],
    qty: 9,
    discount: 0,
  },
  {
    id: 16,
    title: "Ladies Belt",
    image: ["/images/belt.webp"],
    slug: "ladies belt",
    description: "Trendy buckle belt for dresses and jeans",
    price: 350,
    catagory: "accessories",
    size: ["M", "L"],
    color: ["#000000", "#a0522d"],
    qty: 4,
    discount: 10,
  },
  {
    id: 17,
    title: "Stylish Scarf",
    image: ["/images/Scarf.webp"],
    slug: "stylish scarf women",
    description: "Lightweight scarf for all seasons",
    price: 500,
    catagory: "accessories",
    size: ["S", "M", "L"],
    color: ["#ffffff", "#ffa07a"],
    qty: 7,
    discount: 12,
  },
  {
    id: 18,
    title: "Elegant Wrist Watch",
    image: ["/images/watch.avif"],
    slug: "elegant wrist watch",
    description: "Minimal design gold-tone ladies watch",
    price: 2200,
    catagory: "accessories",
    size: ["M", "L"],
    color: ["#d4af37"],
    qty: 3,
    discount: 5,
  },

  // ------- PANTS -------
  {
    id: 19,
    title: "Women Pant",
    image: ["/images/pants.jpg"],
    slug: "women pants",
    description: "Best quality Pants for women",
    price: 300,
    catagory: "pants",
    size: ["S", "M", "L", "XL"],
    color: ["#ffffff", "#000000", "#e60000"],
    qty: 5,
    discount: 0,
  },
  {
    id: 20,
    title: "High Waist Jeans",
    image: ["/images/jeans.jpg"],
    slug: "High Waist Jeans",
    description: "Stretchable high-waist denim jeans",
    price: 850,
    catagory: "pants",
    size: ["S", "M", "L"],
    color: ["#00008b", "#808080"],
    qty: 6,
    discount: 10,
  },
  {
    id: 21,
    title: "Cropped Pants",
    image: ["/images/cropped-pants.jpg"],
    slug: "cropped pants women",
    description: "Elegant cropped pants for casual wear",
    price: 650,
    catagory: "pants",
    size: ["M", "L", "XL"],
    color: ["#696969"],
    qty: 4,
    discount: 5,
  },
  {
    id: 22,
    title: "Slim Fit Trousers",
    image: ["/images/trousers.jpg"],
    slug: "slim fit trousers",
    description: "Professional wear slim-fit trousers",
    price: 780,
    catagory: "pants",
    size: ["S", "M", "L", "XL"],
    color: ["#000000", "#a9a9a9"],
    qty: 5,
    discount: 8,
  },
  {
    id: 23,
    title: "Women Leggings",
    image: ["/images/leggings.webp"],
    slug: "women leggings",
    description: "Comfortable leggings for gym and home",
    price: 500,
    catagory: "pants",
    size: ["S", "M", "L"],
    color: ["#000000", "#ffffff"],
    qty: 9,
    discount: 12,
  },
  {
    id: 24,
    title: "Wide Leg Pants",
    image: ["/images/wide-leg.jpeg"],
    slug: "wide leg pants",
    description: "Stylish wide-leg pants for formal wear",
    price: 900,
    catagory: "pants",
    size: ["M", "L", "XL"],
    color: ["#808000"],
    qty: 7,
    discount: 7,
  },
];
